services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=hutsdev'
      - 'POSTGRES_DB=carPartsEcom'
      - 'POSTGRES_PASSWORD=hutsdev'
    volumes:
      - '.volumes/hutsdev/postgres:/var/lib/postgresql/data'
